
---------- Window 'SLEEP.killing tests (started at 09Jun14:04:21) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:25'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:25.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/grey80) | PEND (grey80)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | RUN (forestville) (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Expected application event 'all tests to be read' occurred, proceeding.
Expected application event 'test Basic to start' occurred, proceeding.

'quit' event created with arguments ''

Changing GUI status to: 'Waiting for all tests to terminate ...'

'quit' event created with arguments ''

Changing GUI status to: 'Waiting for all tests to terminate ...'

Progress bar set to fraction 1.0, text 'All 1 tests completed at 09Jun14:04:28'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/salmon) | no report, possibly killed with SIGKILL (salmon)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (white) | 0 (white) | Check box (checked)
-> Failed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->   Killed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->     no report, possibly killed with SIGKILL (salmon,bold) | 1 (salmon,bold) | Check box (checked)
