<-SRV:TextTest slave server started on 10.67.7.144:35348
<-CMD:cd /nfs/vm/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/texttesttmp/sleep.killing.19Aug112829.16925/slavelogs; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/TargetApp -a sleep.killing -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge.gui/QueueSystems/ErrorHandling/GUI/JobDeletionFails/texttesttmp/sleep.killing.19Aug112829.16925 -servaddr 10.67.7.144:53654""
->OUT:Your job 1 ("stupid") has been submitted.
<-SRV:Completed submission of all tests
->CLI:30897
sleep.killing:Basic
(idefault
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'freeText'
p5
S'Running on forestville'
p6
sS'started'
p7
I1
sS'completed'
p8
I0
sS'briefText'
p9
S'RUN (forestville)'
p10
sS'executionHosts'
p11
(lp12
S'forestville'
p13
asS'lifecycleChange'
p14
S'start'
p15
sb.
<-CMD:qdel 1
->ERR:Somebody has registered the job for deletion
<-CMD:qdel 1
->ERR:denied: job "1" does not exist
