Using LSF queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default LSF queue

Expected application event 'all tests to be read' occurred, proceeding.
Expected application event 'test Basic to become pending' occurred, proceeding.

Generating signal SIGUSR2
Terminating testing due to external interruption (RUNLIMIT2)
T: Cancelling SLEEP.killing test-case Basic in LSF (job 1)
S: SLEEP.killing test-case Basic not compared:
LSF job exited
---------- Full accounting info from LSF ----------
Your job was sent into a large mysterious void. Bad luck.

Creating batch report for application SLEEP ...
File written.
