
---------- Window 'SLEEP.killing tests (started at 09Jun14:04:20) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:24'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:24.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/grey80) | PEND (grey80)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | RUN (geita) (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | USUSP (geita) (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)
->   USUSP (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | RUN (geita) (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)
->   USUSP (white) | 0 (white) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (white) | 0 (white) | Check box (checked)
-> Running (white) | 0 (white) | Check box (checked)
->   USUSP (white) | 0 (white) | Check box (checked)
-> Final filter (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Progress bar set to fraction 1.0, text 'All 1 tests completed at 09Jun14:04:40'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/salmon) | KILLED (salmon)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Initial filter (white) | 0 (white) | Check box (checked)
-> Running (white) | 0 (white) | Check box (checked)
->   USUSP (white) | 0 (white) | Check box (checked)
-> Final filter (white) | 0 (white) | Check box (checked)
-> Failed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->   Killed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->     KILLED (salmon,bold) | 1 (salmon,bold) | Check box (checked)

No longer greyed out : _Save

Changed selection in Test Tree with columns: Tests: All 1 selected, none hidden , Details
-> TargetApp (sleep.killing) (black/white,bold) | (white)
->   Basic (black/salmon) | KILLED (salmon)   ***

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Basic , Details
-> Comparison Files (bold)
->   errors.sleep (DarkSeaGreen2) | (DarkSeaGreen2)
->   output.sleep (salmon) | (salmon)

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========
Test were terminated before completion (KILLED) on geita :
Test killed explicitly at 11:07
---------- Differences in output ----------
1,2c1
< Sleeping for 5 seconds...
< Done
---
> Sleeping for 1000 seconds...
===============================

Expected application event 'completion of test actions' occurred, proceeding.

'quit' event created with arguments ''
