Using Application APP
The following variables may be set by the user :
STORYTEXT_HOME|$TEXTTEST_HOME/storytext|Location to store shortcuts from the GUI
TEXTTEST_DYNAMIC_GUI_INTERPRETER||Alternative interpreter for the dynamic GUI : mostly useful for coverage / testing
TEXTTEST_HOME|.|Alias for TEXTTEST_PATH
TEXTTEST_PATH|$TEXTTEST_HOME|Root directories of the test suite
TEXTTEST_PERSONAL_CONFIG|~/.texttest|Location of personal configuration
TEXTTEST_PERSONAL_LOG|$TEXTTEST_PERSONAL_CONFIG/log|Location to write TextTest's internal logs
TEXTTEST_QS_POLL_WAIT|5|Amount of time to wait before initiating polling of SGE
TEXTTEST_SLAVE_CMD|<source directory>/bin/texttest.py|TextTest start-script for starting subsequent processes
TEXTTEST_TMP|Config value 'default_texttest_tmp'|Location of temporary files from test runs
TEXTTEST_XVFB_WAIT|15|Time to wait for Xvfb to set up connections
The following variables are set by TextTest :
TEXTTEST_CHECKOUT|Full path to the checkout directory
TEXTTEST_CHECKOUT_NAME|Local name of the checkout directory
TEXTTEST_FOLLOW_FILE_TITLE|Title of the window when following file progress
TEXTTEST_ROOT|Full path to the root directory for each test application
TEXTTEST_SANDBOX|Full path to the sandbox directory
TEXTTEST_SANDBOX_ROOT|Full path to the sandbox root directory
TEXTTEST_SUBMIT_COMMAND_ARGS|Exact command arguments to run TextTest slave, for use by proxy
USECASE_RECORD_SCRIPT|Full path to the script to record in GUI tests
USECASE_REPLAY_DELAY|Time to wait between each action in GUI tests
USECASE_REPLAY_SCRIPT|Full path to the script to replay in GUI tests
The following variables can be used in environment files :
QUEUE_SYSTEM_PROCESSES||Deprecated. See "queue_system_processes" in config file docs
QUEUE_SYSTEM_RESOURCE||Deprecated. See "queue_system_resource" in config file docs
QUEUE_SYSTEM_SUBMIT_ARGS||Deprecated. See "queue_system_submit_args" in config file docs
