The following new files/directories were created:
<Test Directory>
----texttesttmp
--------self_test.startdigit.kbrerun.13Aug151702.30077
------------sleep.startdigit.kbrerun
----------------123Test
--------------------errors.sleep
--------------------output.sleep
--------------------framework_tmp
------------------------errors.sleepcmp
------------------------errors.sleeporigcmp
------------------------teststate
