
---------- Window 'HELLO tests under /carm/proj/texttest-tmp/geoff/dynamic_gui.09Jun140245.14502/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillReusedTest/TargetApp/ (started at 09Jun14:04:21) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:25'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:25.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Progress bar set to fraction 0.0, text '0 of 2 tests completed'

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 2 (white,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/grey80) | PEND (grey80)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/LightGoldenrod1) | RUN (sunvalley) (LightGoldenrod1)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Progress bar set to fraction 0.5, text '1 of 2 tests completed'

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (white) | 0 (white) | Check box (checked)
-> Failed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->   Differences (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->     output different (salmon,bold) | 1 (salmon,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)
->   Suite (black/white,bold) | (white)
->     Test (black/LightGoldenrod1) | RUN (sunvalley) (LightGoldenrod1)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)
-> Failed (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->   Differences (salmon,bold) | 1 (salmon,bold) | Check box (checked)
->     output different (salmon,bold) | 1 (salmon,bold) | Check box (checked)

Expected application event 'all tests to be read' occurred, proceeding.
Expected application event 'test Test under Suite to start' occurred, proceeding.
Expected application event 'test Test under TargetApp to complete' occurred, proceeding.

'set test selection to' event created with arguments 'Test under Suite'

No longer greyed out : _Kill

Changed selection in Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)
->   Suite (black/white,bold) | (white)
->     Test (black/LightGoldenrod1) | RUN (sunvalley) (LightGoldenrod1)   ***

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Test , Details
-> Temporary Files

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========
Running on sunvalley

To obtain the latest progress information and an up-to-date comparison of the files above, perform 'recompute status' (press 'F5')
===============================

'kill selected tests' event created with arguments ''

Changing GUI status to: 'Killing 1 tests ...'

Waiting for application event 'completion of test actions' to occur.

Changing GUI status to: 'Performed 'Kill selected tests' on test Suite/Test.'

Greyed out : _Kill
No longer greyed out : _Save

Progress bar set to fraction 1.0, text 'All 2 tests completed at 09Jun14:04:28'

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)
->   Suite (black/white,bold) | (white)
->     Test (black/salmon) | KILLED (salmon)   ***

Updated : File Tree with columns: Test , Details
-> Comparison Files (bold)
->   errors.hello (salmon) | (salmon)
->   output.hello (DarkSeaGreen2) | (DarkSeaGreen2)

========== Text Info ==========
Test were terminated before completion (KILLED) on sunvalley :
Test killed explicitly at 16:32
---------- Differences in errors ----------
0a1,4
> Traceback (most recent call last):
>   File "/carm/proj/texttest-tmp/geoff/texttest.sge.29Apr163219/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillReusedTest/TargetApp//hello.py", line 4, in ?
>     time.sleep(10)
> KeyboardInterrupt
===============================

Expected application event 'completion of test actions' occurred, proceeding.

'quit' event created with arguments ''
