<-SRV:TextTest slave server started on 10.67.18.24:36392
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.sge.10Nov171702.26873/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.10Nov171707.26890/slavelogs; qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/texttest.sge.10Nov171702.26873/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/TargetApp -a sleep.killing -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/texttest.sge.10Nov171702.26873/texttest.sge/QueueSystems/ErrorHandling/Console/PollSlaveCrash/texttesttmp/sleep.killing.10Nov171707.26890 -servaddr 10.67.18.24:33721 -b short_local""
->FIL:sleep.killing.02Jun105522.29337
->OUT:Your job 1 (stupid) has been submitted.
<-SRV:Completed submission of all tests
->FIL:sleep.killing.10Nov171707.26890
<-CMD:qstat
<-CMD:qacct -j 1
->OUT:Some random accounting info
