Using SGE queues for Application SLEEP, version killing
Q: Submitting SLEEP.killing test-case Basic to default SGE queue
S: SLEEP.killing test-case Basic not compared:
SGE job exited
---------- Error messages written by SGE job ----------
Some Beautiful Error Message...
With Extra Nonsense
---------- Full accounting info from SGE ----------
Some random accounting info

Creating batch report for application SLEEP ...
File written.
