Using SGE queues for Application HELLO, checkout /carm/proj/texttest-tmp/geoff/texttest.sge.16Aug104043.27702/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/ResubmitTest/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test succeeded on centreville.carmen.se
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on centreville.carmen.se : differences in output
View details(v), Save(s) or continue(any other key)?
