Using Application HELLO, version refvar.up, checkout /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/SlaveReuse/Slave/AddTestEnvRefUp/TargetApp/
Running HELLO.refvar.up test-suite TargetApp
  Running HELLO.refvar.up test-case Test
Comparing differences for HELLO.refvar.up test-suite TargetApp
  Comparing differences for HELLO.refvar.up test-case Test (on errors.hello,output.hello)
Using Application HELLO, checkout /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/SlaveReuse/Slave/AddTestEnvRefUp/TargetApp/
Running HELLO test-suite TargetApp
  Running HELLO test-suite Suite
    Running HELLO test-case Test
Comparing differences for HELLO test-suite TargetApp
  Comparing differences for HELLO test-suite Suite
    Comparing differences for HELLO test-case Test - SUCCESS! (on errors.hello,output.hello)
Running HELLO.refvar.up test-suite TargetApp
  Running HELLO.refvar.up test-suite Suite
    Running HELLO.refvar.up test-case Test
Comparing differences for HELLO.refvar.up test-suite TargetApp
  Comparing differences for HELLO.refvar.up test-suite Suite
    Comparing differences for HELLO.refvar.up test-case Test - SUCCESS! (on errors.hello,output.hello.refvar)
