Using SGE queues for Application HELLO, checkout /carm/proj/texttest-tmp/geoff/texttest.sge.28Oct152254.17991/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/VirtualDisplayArgs/TargetApp/
Using SGE queues for Application HELLO, version virtdisp, checkout /carm/proj/texttest-tmp/geoff/texttest.sge.28Oct152254.17991/texttest.sge/QueueSystems/SlaveReuse/Master/ForceReuse/Console/VirtualDisplayArgs/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
S: HELLO test-case Test FAILED on kilimanjaro : differences in output
View details(v), Save(s) or continue(any other key)?
Q: Submitting HELLO.virtdisp test-case Test to default SGE queue
S: HELLO.virtdisp test-case Test FAILED on kilimanjaro : differences in output
View details(v), Save Version virtdisp(1), Save(s) or continue(any other key)?
