<-SRV:TextTest slave server started on 10.67.7.144:50215
<-CMD:cd /nfs/vm/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge/QueueSystems/ErrorHandling/Console/Killing/JobDisappearsAfterStart/texttesttmp/sleep.killing.19Aug112822.16751/slavelogs; env --unset=USECASE_RECORD_SCRIPT --unset=USECASE_REPLAY_SCRIPT qsub -N Test-Basic-SLEEP.killing -w e -notify -m n -cwd -b y -V -o Test-Basic-SLEEP.killing.log -e Test-Basic-SLEEP.killing.errors "exec $SHELL -c "exec /users/geoff/work/master/Testing/TextTest/bin/texttest.py -d /carm/proj/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge/QueueSystems/ErrorHandling/Console/Killing/JobDisappearsAfterStart/TargetApp -a sleep.killing -l -tp 'Basic' -slave /carm/proj/texttest-tmp/geoff/dynamic_gui.19Aug112801.5006/texttest.sge/QueueSystems/ErrorHandling/Console/Killing/JobDisappearsAfterStart/texttesttmp/sleep.killing.19Aug112822.16751 -servaddr 10.67.7.144:58024 -b short_local""
->OUT:Your job 1 ("stupid") has been submitted.
<-SRV:Completed submission of all tests
->CLI:9064
sleep.killing:Basic
(idefault
Running
p1
(dp2
S'category'
p3
S'running'
p4
sS'freeText'
p5
S'Running on bellville'
p6
sS'started'
p7
I1
sS'completed'
p8
I0
sS'briefText'
p9
S'RUN (bellville)'
p10
sS'executionHosts'
p11
(lp12
S'bellville'
p13
asS'lifecycleChange'
p14
S'start'
p15
sb.
<-CMD:qdel 1
->ERR:No jobs can be deleted today!
<-CMD:qacct -j 1
->OUT:Seriously nasty things happened while this test was running!
