Using Application HELLO, version 1
Reconnecting to test results in directory /carm/proj/texttest-tmp/geoff/texttest.sge.28Jul105022.22705/texttest.sge/QueueSystems/SlaveReuse/Slave/AddApplicationReconnect/texttesttmp/console.28Jul104553.22544/hello.1
Reconnecting to HELLO.1 test-suite TargetApp
  Reconnecting to HELLO.1 test-case Test (state failure)
Using Application HELLO, version 2
Reconnecting to test results in directory /carm/proj/texttest-tmp/geoff/texttest.sge.28Jul105022.22705/texttest.sge/QueueSystems/SlaveReuse/Slave/AddApplicationReconnect/texttesttmp/console.28Jul104553.22544/hello.2
Reconnecting to HELLO.2 test-suite TargetApp
  Reconnecting to HELLO.2 test-suite Suite
    Reconnecting to HELLO.2 test-case Test (state success)
Write directory /carm/proj/texttest-tmp/geoff/texttest.sge.28Jul105022.22705/texttest.sge/QueueSystems/SlaveReuse/Slave/AddApplicationReconnect/texttesttmp/console.1.28Jul105027.22708/hello.2/Suite/Test externally removed
