The following new files/directories were created:
<Test Directory>
----texttesttmp
--------console.absdata.queuesystem.30Apr164213.18264
------------tdat.absdata.queuesystem
----------------Test2
--------------------errors.tdat
--------------------output.tdat
--------------------testdata.py
--------------------framework_tmp
------------------------catalogue.tdatorigcmp
------------------------errors.tdatcmp
------------------------errors.tdatorigcmp
------------------------options.tdatorigcmp
------------------------output.tdatcmp
------------------------output.tdatorigcmp
