TextTest will write diagnostics in /carm/proj/texttest/geoff/texttesttmp/texttest.01Oct173346/texttest.lsf/QueueSystems/ErrorHandling/Console/OtherAppDefaultConfig based on file at /carm/proj/texttest/geoff/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application HELLO
Q: Submitting HELLO test-case Test to default LSF queue
S: HELLO test-case Test FAILED on forestville : differences in output
View details(v), Save(s) or continue(any other key)?
