The following new files/directories were created:
<Test Directory>
----texttesttmp
--------console.env.queuesystem.30Apr164213.27207
------------tdat.env.queuesystem
----------------Test2
--------------------catalogue.tdat
--------------------errors.tdat
--------------------output.tdat
--------------------framework_tmp
------------------------catalogue.tdatcmp
------------------------catalogue.tdatorigcmp
------------------------environment.tdatorigcmp
------------------------errors.tdatcmp
------------------------errors.tdatorigcmp
------------------------options.tdatorigcmp
------------------------output.tdatcmp
------------------------output.tdatorigcmp
