
---------- Window 'SLEEP tests (started at 09Jun14:04:20) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:24'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:24.' , Image 'throbber_inactive.png'
--------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep) (black/white,bold) | (white)
->   Basic (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Expected application event 'test Basic to be read' occurred, proceeding.
Expected application event 'test configuration to be read' occurred, proceeding.

'set test selection to' event created with arguments 'Basic'

Waiting for application event 'completion of test actions' to occur.

No longer greyed out : _Kill

Changed selection in Test Tree with columns: Tests: All 1 selected, none hidden , Details
-> TargetApp (sleep) (black/white,bold) | (white)
->   Basic (black/white) | (white)   ***

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Basic , Details
-> Temporary Files

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========

Description:
<No description provided>

Full path:
Basic
===============================

Updated : Test Tree with columns: Tests: All 1 selected, none hidden , Details
-> TargetApp (sleep) (black/white,bold) | (white)
->   Basic (black/grey80) | PEND (grey80)   ***

Updated : File Tree with columns: Basic , Details
-> Temporary Files

========== Text Info ==========
Job pending in SGE
===============================

Updated : Test Tree with columns: Tests: All 1 selected, none hidden , Details
-> TargetApp (sleep) (black/white,bold) | (white)
->   Basic (black/LightGoldenrod1) | RUN (painesville) (LightGoldenrod1)   ***

Updated : File Tree with columns: Basic , Details
-> Temporary Files

========== Text Info ==========
Running on painesville

To obtain the latest progress information and an up-to-date comparison of the files above, perform 'recompute status' (press 'F5')
===============================

Greyed out : _Kill

Progress bar set to fraction 1.0, text 'All 1 tests completed at 09Jun14:04:26'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (sleep) (black/white,bold) | All 1 tests successful (DarkSeaGreen2)

Current page changed in Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
-> Not started (white) | 0 (white) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (white) | 0 (white) | Check box (checked)
-> Succeeded (DarkSeaGreen2,bold) | 1 (DarkSeaGreen2,bold) | Check box (checked)

Expected application event 'completion of test actions' occurred, proceeding.

'quit' event created with arguments ''
