Using SGE queues for Application PERF
Q: Submitting PERF test-case 1Minute to default SGE queue
Q: Submitting PERF test-case 5Minutes to default SGE queue
S: PERF test-case 5Minutes not compared:
Failed to submit to SGE (Unable to run job: unknown resource "performance_resource".)
Submission command was 'qsub -N Test-5Minutes-PERF -l performance_resource -w e -notify -m n -cwd -b y -V -o Test-5Minutes-PERF.log -e Test-5Minutes-PERF.errors ... '

Q: Submitting PERF test-case NoLogFile to default SGE queue
S: PERF test-case NoLogFile not compared:
Failed to submit to SGE (Unable to run job: unknown resource "performance_resource".)
Submission command was 'qsub -N Test-NoLogFile-PERF -l performance_resource -w e -notify -m n -cwd -b y -V -o Test-NoLogFile-PERF.log -e Test-NoLogFile-PERF.errors ... '

S: PERF test-case 1Minute FAILED on perf_machine1 : new results in logperf
View details(v), Save(s) or continue(any other key)?
