Using SGE queues for Application HELLO, checkout /carm/proj/texttest-tmp/geoff/texttest.30Mar153906.11545/texttest.sge/QueueSystems/SlaveReuse/Master/AllowRacing/BasicReuse/TargetApp/
Q: Submitting HELLO test-case Test to default SGE queue
Waiting Q thread for 5 seconds
S: HELLO test-case Test FAILED on tiptonville : differences in output
View details(v), Save(s) or continue(any other key)?
S: HELLO test-case Test succeeded on morafenobe
