Top Window title is TextTest dynamic GUI (tests started at 11Jun18:06:47)
Default widget is <type 'gtk.TreeView'>
Setting window width to 60% of screen.
Setting window height to 83% of screen.

Viewing toggle action with title '_Toolbar'
Viewing toggle action with title '_Shortcut bar'
Viewing toggle action with title '_Status bar'
Viewing action with title '_Quit', stock id ''gtk-quit'', accelerator ''<control>q''
Viewing action with title 'View File' (greyed out)
Viewing action with title 'View Filtered File' (greyed out)
Viewing action with title 'View Raw Differences' (greyed out)
Viewing action with title 'View Differences' (greyed out)
Viewing action with title 'Follow File Progress' (greyed out)
Viewing action with title '_Save', stock id ''gtk-save'', accelerator ''<control>s'' (greyed out)
Viewing action with title 'S_ave Selection...', stock id ''gtk-save-as'', accelerator ''<control><shift>s'' (greyed out)
Viewing action with title '_Kill', stock id ''gtk-stop'' (greyed out)
Viewing action with title '_Migration Notes'
Viewing action with title 'Component _Versions'
Viewing action with title '_About TextTest', stock id ''gtk-about''

UI layout: 
<ui>
  <menubar name="MainMenuBar">
    <menu name="filemenu" action="filemenu">
      <placeholder name="FirstInFileMenu">
        <menuitem name="Save" action="Save"/>
        <separator/>
      </placeholder>
      <menuitem name="Save Selection..." action="Save Selection..."/>
      <separator/>
      <menuitem name="Quit" action="Quit"/>
    </menu>
    <menu name="editmenu" action="editmenu">
    </menu>
    <menu name="viewmenu" action="viewmenu">
      <menuitem name="Toolbar" action="Toolbar"/>
      <menuitem name="Shortcut bar" action="Shortcut bar"/>
      <menuitem name="Status bar" action="Status bar"/>
    </menu>
    <menu name="actionsmenu" action="actionsmenu">
      <menuitem name="Kill" action="Kill"/>
    </menu>
    <placeholder name="ExtraMenus">
    </placeholder>
    <menu name="helpmenu" action="helpmenu">
      <menuitem name="Migration Notes" action="Migration Notes"/>
      <separator/>
      <menuitem name="Component Versions" action="Component Versions"/>
      <separator/>
      <menuitem name="About TextTest" action="About TextTest"/>
    </menu>
  </menubar>
  <toolbar name="MainToolBar">
    <toolitem name="Quit" action="Quit"/>
    <toolitem name="Kill" action="Kill"/>
    <toolitem name="Save" action="Save"/>
    <separator/>
  </toolbar>
  <popup name="TestPopupMenu">
  </popup>
  <popup name="TestFilePopupMenu">
    <menuitem name="View File" action="View File"/>
    <menuitem name="View Filtered File" action="View Filtered File"/>
    <separator/>
    <menuitem name="View Differences" action="View Differences"/>
    <menuitem name="View Raw Differences" action="View Raw Differences"/>
    <separator/>
    <menuitem name="Follow File Progress" action="Follow File Progress"/>
  </popup>
</ui>

Progress bar set to fraction 0.0, text '0 of 3 tests completed'

Test Tree description...
-> TargetApp (hello)
->   Suite1
->     Test1
->     Test2
->   Suite2
->     Test2

Test column header set to 'Tests: 0/3 selected, none hidden'

Pane separator positioned 50% from the left edge

Tabs showing : Status

Test progress:
--> Not started : 3, colour 'white', font 'bold'

Changing GUI status to: 'TextTest started at 11Jun18:06:47.'

Waiting for application event 'test Test1 to become pending' to occur.
Redrawing test Test1 coloured white
(Second column 'PEND' coloured white)

Test progress:
--> Not started : 2, colour 'white', font 'bold'
--> Pending : 1, colour 'white', font 'bold'
Expected application event 'test Test1 to become pending' occurred, proceeding.

'quit' event created with arguments ''

Changing GUI status to: 'Killing 3 tests ...'
Killing HELLO test-case Test2
Killing HELLO test-case Test2
Killing HELLO test-case Test1

Changing GUI status to: 'Killed 3 tests.'

Changing GUI status to: 'Waiting for all tests to terminate ...'
Redrawing test Test2 coloured red
(Second column 'cancelled' coloured red)

Progress bar set to fraction 0.333333333333, text '1 of 3 tests completed (1 tests failed)'

Test progress:
--> Not started : 1, colour 'white', font 'bold'
--> Pending : 1, colour 'white', font 'bold'
--> Failed : 1, colour 'red', font 'bold'
----> Cancelled : 1, colour 'red', font 'bold'
------> cancelled : 1, colour 'red', font 'bold'
Redrawing test Test2 coloured red
(Second column 'cancelled' coloured red)

Progress bar set to fraction 0.666666666667, text '2 of 3 tests completed (2 tests failed)'

Test progress:
--> Not started : 0, colour 'white', font ''
--> Pending : 1, colour 'white', font 'bold'
--> Failed : 2, colour 'red', font 'bold'
----> Cancelled : 2, colour 'red', font 'bold'
------> cancelled : 2, colour 'red', font 'bold'
Redrawing test Test1 coloured red
(Second column 'cancelled pending job at 18:06' coloured red)

Progress bar set to fraction 1.0, text 'All 3 tests completed at 11Jun18:06:54 (3 tests failed)'

Test progress:
--> Not started : 0, colour 'white', font ''
--> Pending : 0, colour 'white', font ''
--> Failed : 3, colour 'red', font 'bold'
----> Cancelled : 3, colour 'red', font 'bold'
------> cancelled : 2, colour 'red', font 'bold'
------> cancelled pending job at 18:06 : 1, colour 'red', font 'bold'

Changing GUI status to: 'Removing all temporary files ...'
