TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.lsf.13Jun123443/QueueSystems/ErrorHandling/GUI/QuitDuringSetup based on file at /users/geoff/work/master/Testing/Automatic/texttest/logging.texttest
Using LSF queues for Application HELLO
Q: Submitting test Test1 to default LSF queue
Q: Submitting test Test2 under Suite1 to default LSF queue
T: Cancelling test Test1 in LSF (job 1)
