
---------- Window 'HELLO tests under /carm/proj/texttest-tmp/geoff/dynamic_gui.09Jun140245.14502/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/KillAndContinue/TargetApp/ (started at 09Jun14:04:26) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:30'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:30.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Progress bar set to fraction 0.0, text '0 of 2 tests completed'

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 2 (white,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/grey80) | PEND (grey80)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box (checked)

Expected application event 'all tests to be read' occurred, proceeding.
Expected application event 'test Test under TargetApp to become pending' occurred, proceeding.

'set test selection to' event created with arguments 'Test under TargetApp (hello)'

No longer greyed out : _Kill

Changed selection in Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/grey80) | PEND (grey80)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Test , Details
-> Temporary Files

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========
Job pending in SGE
===============================

'kill selected tests' event created with arguments ''

Changing GUI status to: 'Killing 1 tests ...'

Waiting for application event 'test Test under Suite to become pending' to occur.
Waiting for application event 'test Test under TargetApp to complete' to occur.

Changing GUI status to: 'Performed 'Kill selected tests' on test Test.'

Greyed out : _Kill

Progress bar set to fraction 0.5, text '1 of 2 tests completed'

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | cancelled pending job at 14:04 (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : File Tree with columns: Test , Details
-> Temporary Files

========== Text Info ==========
Test were cancelled before starting :
Test job 9019 was cancelled (while still pending in SGE) at 14:04
===============================

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | cancelled pending job at 14:04 (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/grey80) | PEND (grey80)

Expected application event 'test Test under Suite to become pending' occurred, proceeding.
Expected application event 'test Test under TargetApp to complete' occurred, proceeding.

'quit' event created with arguments ''

Changing GUI status to: 'Waiting for all tests to terminate ...'

Progress bar set to fraction 1.0, text 'All 2 tests completed at 09Jun14:04:34'

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | cancelled pending job at 14:04 (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/salmon) | cancelled pending job at 14:04 (salmon)
