killed=1
13Nov2007
SLEEP killing3 : 1 tests : 1 killed

Summary of all Unsuccessful tests follows...
---------------------------------------------------------------------------------
The following tests were terminated before completion : 
In SLEEP.killing3 test-suite TargetApp:
  - SLEEP.killing3 test-case Basic : RUNLIMIT


Details of all Unsuccessful tests follows...
---------------------------------------------------------------------------------

Detailed information for the tests that were terminated before completion follows...
--------------------------------------------------------
TEST were terminated before completion (RUNLIMIT) on dolgeville : SLEEP.killing3 test-case Basic (under Basic)
Test exceeded maximum wallclock time allowed by SGE (s_rt parameter)
---------- Differences in output ----------
1,2c1
< Sleeping for 5 seconds...
< Done
---
> Sleeping for 1000 seconds...

