
---------- Window 'HELLO tests under /carm/proj/texttest-tmp/geoff/dynamic_gui.09Jun140245.14502/texttest.sge.gui/QueueSystems/SlaveReuse/Master/ForceReuse/GUI/JobKillBeforeReuse/TargetApp/ (started at 09Jun14:04:20) - TextTest dynamic GUI' ----------
Focus widget is 'Test Tree'

Menu Bar : '_File' (+) , '_View' (+) , '_Actions' (+) , '_Help' (+)

Tool Bar :
  _Quit (Stock image 'gtk-quit', accelerator 'Ctrl+Q', tooltip 'Quit')
  _Kill (Stock image 'gtk-stop', greyed out, accelerator 'Ctrl+Delete', tooltip 'Kill selected tests')
  _Save (Stock image 'gtk-save', greyed out, accelerator 'Ctrl+S', tooltip 'Save results for selected tests')
  Progress bar set to fraction 0.0, text 'All 0 tests completed at 09Jun14:04:24'
...........

Showing Test Tree with columns: Tests: All 0 selected , Details

------------------------------ (vertical pane separator)
...........

Showing Notebook with tabs: Status , Selection , Run Info
Viewing page 'Status'

Showing Test Status View with columns: Status , Number , Visible
'Shortcuts:' , Button '_New'
...........
'TextTest started at 09Jun14:04:24.' , Image 'throbber_inactive.png'
----------------------------------------------------------------------------------------------------

Progress bar set to fraction 0.0, text '0 of 1 tests completed'

Updated : Test Tree with columns: Tests: 0/1 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)

Progress bar set to fraction 0.0, text '0 of 2 tests completed'

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/white) | (white)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 2 (white,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/grey80) | PEND (grey80)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (grey80,bold) | 1 (grey80,bold) | Check box (checked)

Updated : Test Tree with columns: Tests: 0/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/LightGoldenrod1) | RUN (withamfield) (LightGoldenrod1)
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : Test Status View with columns: Status , Number , Visible
-> Not started (white,bold) | 1 (white,bold) | Check box (checked)
-> Pending (white) | 0 (white) | Check box (checked)
-> Running (LightGoldenrod1,bold) | 1 (LightGoldenrod1,bold) | Check box (checked)

Expected application event 'all tests to be read' occurred, proceeding.
Expected application event 'test Test under TargetApp to start' occurred, proceeding.

'set test selection to' event created with arguments 'Test under TargetApp (hello)'

No longer greyed out : _Kill

Changed selection in Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/LightGoldenrod1) | RUN (withamfield) (LightGoldenrod1)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Current page changed in Notebook with tabs: Test , Status , Selection , Run Info
Viewing page 'Test'
...........

Showing File Tree with columns: Test , Details
-> Temporary Files

------------------------------ (horizontal pane separator)
...........

========== Text Info ==========
Running on withamfield

To obtain the latest progress information and an up-to-date comparison of the files above, perform 'recompute status' (press 'F5')
===============================

'kill selected tests' event created with arguments ''

Changing GUI status to: 'Killing 1 tests ...'

Waiting for application event 'completion of test actions' to occur.

Changing GUI status to: 'Performed 'Kill selected tests' on test Test.'

Greyed out : _Kill
No longer greyed out : _Save

Progress bar set to fraction 0.5, text '1 of 2 tests completed'

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/white) | (white)

Updated : File Tree with columns: Test , Details
-> Comparison Files (bold)
->   errors.hello (DarkSeaGreen2) | (DarkSeaGreen2)
->   output.hello (salmon) | (salmon)

========== Text Info ==========
Test FAILED on withamfield :
---------- Differences in output ----------
1c1
< Hello
---
> Hello World!
===============================

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/grey80) | PEND (grey80)

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)   ***
->   Suite (black/white,bold) | (white)
->     Test (black/LightGoldenrod1) | RUN (withamfield) (LightGoldenrod1)

Progress bar set to fraction 1.0, text 'All 2 tests completed at 09Jun14:04:28'

Updated : Test Tree with columns: Tests: 1/2 selected, none hidden , Details
-> TargetApp (hello) (black/white,bold) | (white)
->   Test (black/salmon) | output different (salmon)   ***
->   Suite (black/white,bold) | All 1 tests successful (DarkSeaGreen2)

Expected application event 'completion of test actions' occurred, proceeding.

'quit' event created with arguments ''
